# Generated by Django 5.2.4 on 2025-07-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='ID del Activo')),
                ('asset_type', models.CharField(choices=[('computer', 'Computadora'), ('software', 'Software'), ('contract', 'Contrato'), ('network_device', 'Dispositivo de Red'), ('server', 'Servidor'), ('printer', 'Impresora'), ('mobile_device', 'Dispositivo Móvil'), ('peripheral', 'Periférico'), ('other', 'Otro')], default='computer', max_length=20, verbose_name='Tipo de Activo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(default='Activo', max_length=50, verbose_name='Estado')),
                ('connectivity', models.BooleanField(default=True, verbose_name='Conectividad (Online)')),
                ('antivirus_enabled', models.BooleanField(default=True, verbose_name='Antivirus Habilitado')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('warranty_expiry_date', models.DateField(blank=True, null=True, verbose_name='Fin de Garantía')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Contrato')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Física')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='Dirección MAC')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Asignado A')),
            ],
            options={
                'verbose_name': 'Activo de TI',
                'verbose_name_plural': 'Activos de TI',
                'ordering': ['name'],
            },
        ),
    ]
