# Generated by Django 5.2.4 on 2025-07-14 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('medical_license', models.CharField(max_length=50, unique=True, verbose_name='Licencia Médica')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoría de Examen')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Examen',
                'verbose_name_plural': 'Categorías de Exámenes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Examen')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código de Examen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_items', to='medical.examcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de Examen',
                'verbose_name_plural': 'Ítems de Examen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('patient_rut', models.CharField(max_length=20, verbose_name='RUT del Paciente')),
                ('patient_dob', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento del Paciente')),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Paciente')),
                ('patient_prevencion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Previsión')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones / Justificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_requests', to='medical.doctor', verbose_name='Médico Solicitante')),
                ('selected_exams', models.ManyToManyField(blank=True, related_name='imaging_requests', to='medical.examitem', verbose_name='Exámenes Seleccionados')),
            ],
            options={
                'verbose_name': 'Solicitud de Imagenología',
                'verbose_name_plural': 'Solicitudes de Imagenología',
                'ordering': ['-request_date', 'patient_name'],
            },
        ),
    ]
