# Generated by Django 5.2.4 on 2025-07-15 11:45

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImagingRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('patient_rut', models.CharField(max_length=20, verbose_name='RUT del Paciente')),
                ('patient_dob', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento del Paciente')),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Paciente')),
                ('patient_prevencion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Previsión')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones / Justificación')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.doctor', verbose_name='Médico Solicitante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Solicitud de Imagenología',
                'verbose_name_plural': 'historical Solicitudes de Imagenología',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
