# Generated by Django 5.2.4 on 2025-07-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_historicalimagingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalimagingrequest',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='imagingrequest',
            name='patient_dob',
        ),
    ]
