# Generated by Django 5.2.4 on 2025-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_historicalimagingrequest_patient_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimagingrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagingrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
