# Generated by Django 5.2.4 on 2025-07-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_license',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Licencia Médica'),
        ),
    ]
