# Generated by Django 5.2.4 on 2025-07-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación/Oficina')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión')),
            ],
        ),
    ]
