# Generated by Django 5.2.4 on 2025-07-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_license',
            field=models.BooleanField(default=False, verbose_name='Licencia Médica'),
        ),
    ]
