# Generated by Django 5.2.4 on 2025-07-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_medical_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='medical_license',
        ),
    ]
